# 工作流程

- 提交任务，基于懒加载机制（可以设置创建线程池的时候提前创建），判断长期工是否达到上限，没达到则创建，达到了则加入任务队列；
- 如果任务队列已满，则判断临时工是否达到上限，没达到，创建临时工，达到，执行拒绝策略。

# 原理

每个线程执行的是worker对象的run方法，在worker的run方法中，会从任务队列中取task，执行task的run方法。套娃......

[一部分摘抄自](https://juejin.im/post/5d4e5c9de51d453c11684c25)

# 异常处理
### UncaughtExceptionHandler
我们都知道Runnable接口中的run方法是不允许抛出异常的，因此派生出这个线程的主线程可能无法直接获得该线程在执行过程中的异常信息。如下例：
```java
public static void main(String[] args) throws Exception {
    Thread thread = new Thread(() -> {
        Uninterruptibles.sleepUninterruptibly(2, TimeUnit.SECONDS);
        System.out.println(1 / 0); // 这行会导致报错！
    });
    thread.setUncaughtExceptionHandler((t, e) -> {
        e.printStackTrace(); //如果你把这一行注释掉，这个程序将不会抛出任何异常.
    });
    thread.start();
}
```

为什么会这样呢？其实我们看一下Thread中的源码就会发现，Thread在执行过程中如果遇到了异常，会先判断当前线程是否有设置UncaughtExceptionHandler，如果没有，则会从线程所在的ThreadGroup中获取。（**注意：**每个线程都有自己的ThreadGroup，即使你没有指定，并且它实现了UncaughtExceptionHandler接口）我们看下ThreadGroup中默认的对UncaughtExceptionHandler接口的实现：
```java
public void uncaughtException(Thread t, Throwable e) {
    if (parent != null) {
        parent.uncaughtException(t, e);
    } else {
        Thread.UncaughtExceptionHandler ueh =
            Thread.getDefaultUncaughtExceptionHandler();
        if (ueh != null) {
            ueh.uncaughtException(t, e);
        } else if (!(e instanceof ThreadDeath)) {
            System.err.print("Exception in thread \""
                             + t.getName() + "\" ");
            e.printStackTrace(System.err);
        }
    }
}
```

这个ThreadGroup如果有父`ThreadGroup`，则调用父`ThreadGroup`的`uncaughtException`，否则调用全局默认的`Thread.DefaultUncaughtExceptionHandler`，如果全局的handler也没有设置，则只是简单地将异常信息定位到`System.err`中，这就是为什么我们应当在创建线程的时候，去实现它的`UncaughtExceptionHandler`接口的原因，这么做可以让你更方便地去排查问题。

### 通过execute提交任务给线程池
问题：如果我们向线程池提交的任务中，没有对异常进行`try...catch`处理，并且运行的时候出现了异常，会对线程池造成什么影响？

答案：没有影响，线程池依旧可以正常工作，但是异常却被吞掉了。这通常来说不是一个好事情，因为我们需要拿到原始的异常对象去分析问题。

问题：怎样拿到原始异常对象？

答案：从线程池的源码着手。

```java
// java.util.concurrent.ThreadPoolExecutor#runWorker
final void runWorker(Worker w) {
  	// 当前线程
    Thread wt = Thread.currentThread();
  	// worker工作台 持有的 第一个任务
    Runnable task = w.firstTask;
  	// 把第一个任务清空
    w.firstTask = null;
  	// 先解锁
    w.unlock(); // allow interrupts
  	// 标记
    boolean completedAbruptly = true;
    try {
      	// 循环从【用户任务】队列获取【用户任务】来执行。
        while (task != null || (task = getTask()) != null) {
            // 模板方法模式
          	// 1. 加锁
            w.lock();
            // If pool is stopping, ensure thread is interrupted;
            // if not, ensure thread is not interrupted.  This
            // requires a recheck in second case to deal with
            // shutdownNow race while clearing interrupt
            if ((runStateAtLeast(ctl.get(), STOP) ||
                 (Thread.interrupted() &&
                  runStateAtLeast(ctl.get(), STOP))) &&
                !wt.isInterrupted())
                wt.interrupt();
            try {
              	// 2. 在执行【用户任务】之前可以做一些前置工作
                beforeExecute(wt, task);
                Throwable thrown = null;
                try {
                  	// 3. 执行【用户任务】
                  	// 如果抛出异常，则捕获
                    task.run();
                } catch (RuntimeException x) {
                    thrown = x; throw x;
                } catch (Error x) {
                    thrown = x; throw x;
                } catch (Throwable x) {
                    thrown = x; throw new Error(x);
                } finally {
                  	// 4. 执行完【用户任务】之后，做一些后置工作。
                  	// protected 类型的空实现，官方注释推荐继承ThreadPoolExecutor的子类实现。
                    afterExecute(task, thrown);
                }
            } finally {
                // 5. 把【用户任务】引用清空
                task = null;
                // 做过的【用户任务】数加1
                w.completedTasks++;
                w.unlock();
            }
        }
        completedAbruptly = false;
    } finally {
        // 做一些【默认任务】退出后的工作
        processWorkerExit(w, completedAbruptly);
    }
}
```
重点关注下 afterExecute 方法。在执行任务过程中，一旦抛出任何类型的异常，都会提交给afterExecute这个方法。这个方法不能随意去实现，需要遵循一定的步骤，具体的官方注释也有讲，这里摘抄如下：
```java
/**
 *  <pre> {@code
 * class ExtendedExecutor extends ThreadPoolExecutor {
 *   // ...
 *   protected void afterExecute(Runnable r, Throwable t) {
 *     super.afterExecute(r, t);
 *     if (t == null && r instanceof Future<?>) {
 *       try {
 *         Object result = ((Future<?>) r).get();
 *       } catch (CancellationException ce) {
 *           t = ce;
 *       } catch (ExecutionException ee) {
 *           t = ee.getCause();
 *       } catch (InterruptedException ie) {
 *           Thread.currentThread().interrupt(); // ignore/reset
 *       }
 *     }
 *     if (t != null)
 *       System.out.println(t);
 *   }
 * }}</pre>
 */
```

那么通过这种方式，就可以将原先可能被线程池吞掉的异常成功捕获到，从而便于排查问题。

但这里有个小问题，在runWorker方法中，执行task.run()语句之后，各种类型的异常都被抛出了，这些异常去哪了？最终会被传入到Thread的dispatchUncaughtException方法中，源码如下：
```java
private void dispatchUncaughtException(Throwable e) {
    getUncaughtExceptionHandler().uncaughtException(this, e);
}
```

可以看到它会去获取UncaughtExceptionHandler的实现类，然后调用其中的uncaughtException方法，这也就回到了我们上一小节所分析的UncaughtExceptionHandler实现的具体逻辑。那么为了拿到最原始的异常对象，除了实现UncaughtExceptionHandler接口之外，也可以考虑实现afterExecute方法。
通过submit提交任务到线程池：
这个同样很简单，我们还是先回到submit方法的源码：

```java
public <T> Future<T> submit(Callable<T> task) {
    if (task == null) throw new NullPointerException();
    RunnableFuture<T> ftask = newTaskFor(task);
    execute(ftask);
    return ftask;
}
```

这里的execute方法调用的是 ThreadPoolExecutor 中的execute方法，执行逻辑跟通过execute提交任务到线程池是一样的。我们先重点关注这里的 newTaskFor 方法，其源码如下：
```java
protected <T> RunnableFuture<T> newTaskFor(Callable<T> callable) {
    return new FutureTask<T>(callable);
}
```

可以看到提交的Callable对象用 FutureTask 封装起来了。那么我们知道最终会执行到上述 runWorker 这个方法中，并且最核心的执行逻辑就是task.run();这行代码。我们知道这里的task其实是FutureTask类型，因此我们有必要看一下FutureTask中的run方法的实现：
```java
public void run() {
    if (state != NEW ||
        !UNSAFE.compareAndSwapObject(this, runnerOffset,
                                     null, Thread.currentThread()))
        return;
    try {
        Callable<V> c = callable;
        if (c != null && state == NEW) {
            V result;
            boolean ran;
            try {
                result = c.call();
                ran = true;
            } catch (Throwable ex) {
                result = null;
                ran = false;
              	// 和异常相关最关键的代码
                setException(ex);
            }
            if (ran)
                set(result);
        }
    } finally {
        // runner must be non-null until state is settled to
        // prevent concurrent calls to run()
        runner = null;
        // state must be re-read after nulling runner to prevent
        // leaked interrupts
        int s = state;
        if (s >= INTERRUPTING)
            handlePossibleCancellationInterrupt(s);
    }
}

protected void setException(Throwable t) {
    if (UNSAFE.compareAndSwapInt(this, stateOffset, NEW, COMPLETING)) {
      	// 最关键的地方：将异常对象赋值给了outcome。outcome是FutureTask中的成员变量。
        outcome = t;
        UNSAFE.putOrderedInt(this, stateOffset, EXCEPTIONAL); // final state
        finishCompletion();
    }
}
```

我们通过调用submit方法，拿到一个Future对象之后，再调用它的get方法。

```java
// get方法
public V get() throws InterruptedException, ExecutionException {
    int s = state;
    if (s <= COMPLETING)
        s = awaitDone(false, 0L);
  	// 最终调用了report方法
    return report(s);
}
// 最核心方法。
private V report(int s) throws ExecutionException {
    Object x = outcome;
    if (s == NORMAL)
        return (V)x;
    if (s >= CANCELLED)
        throw new CancellationException();
    throw new ExecutionException((Throwable)x);
}
```

上面是一些状态判断，如果当前任务不是正常执行完毕，或者被取消的话，那么这里的x其实就是原始的异常对象，可以看到会被ExecutionException包装。因此在你调用get方法时，可能会抛出ExecutionException异常，那么调用它的getCause方法就可以拿到最原始的异常对象了。

综上所述，针对提交给线程池的任务可能会抛出异常这一问题，主要有以下2种处理思路：

- 在提交的任务中catch，缺点是如果提交多种类型的任务，每种类型的任务都需要将异常catch，比较繁琐。而且如果只是catch(Exception e)，可能依然会漏掉一些包括Error类型的异常，那为了保险起见，你可以考虑catch(Throwable t).
- 自行实现线程池的afterExecute方法，或者实现Thread的UncaughtExceptionHandler接口。

下面给出我个人创建线程池的一个示例，供大家参考：
```java
import com.google.common.util.concurrent.ThreadFactoryBuilder;
import com.google.common.util.concurrent.Uninterruptibles;
import lombok.extern.slf4j.Slf4j;

import java.util.concurrent.*;

@Slf4j
public class TestThreadPool {
    private static final int DEFAULT_CORE_POOL_SIZE = 12;
    private static final int DEFAULT_MAX_POOL_SIZE = 18;
    private static final int DEFAULT_QUEUE_SIZE = 1000;

    public static void main(String[] args) {
        // 有界阻塞任务队列
        BlockingQueue<Runnable> TASK_QUEUE = new ArrayBlockingQueue<>(DEFAULT_QUEUE_SIZE);
        // 工厂
        ThreadFactory THREAD_FACTORY = new ThreadFactoryBuilder()
                .setThreadFactory(new ThreadFactory() {
                    private int count = 0;

                    @Override
                    public Thread newThread(Runnable r) {
                        String prefix = "StatisticsTask";
                        return new Thread(r, prefix + "-" + count++);
                    }
                })
                // 设置异常处理
                .setUncaughtExceptionHandler((t, e) -> {
                    String threadName = t.getName();
                    log.error("statisticsThreadPool error occurred! threadName: {}, error msg: {}", threadName, e.getMessage(), e);
                }).build();
        // 拒绝策略
        RejectedExecutionHandler HANDLER = (r, executor) -> {
            if (!executor.isShutdown()) {
                log.warn("statisticsThreadPool is too busy! waiting to insert task to queue! ");
                Uninterruptibles.putUninterruptibly(executor.getQueue(), r);
            }
        };
        // 创建工厂
        ThreadPoolExecutor statisticsThreadPool = new ThreadPoolExecutor(DEFAULT_CORE_POOL_SIZE, DEFAULT_MAX_POOL_SIZE,
                60, TimeUnit.SECONDS, TASK_QUEUE, THREAD_FACTORY, HANDLER) {
            //
            @Override
            protected void afterExecute(Runnable r, Throwable t) {
                super.afterExecute(r, t);
                if (t == null && r instanceof Future<?>) {
                    try {
                        Future<?> future = (Future<?>) r;
                        future.get();
                    } catch (CancellationException ce) {
                        t = ce;
                    } catch (ExecutionException ee) {
                        t = ee.getCause();
                    } catch (InterruptedException ie) {
                        Thread.currentThread().interrupt(); // ignore/reset
                    }
                }
                if (t != null) {
                    log.error("statisticsThreadPool error msg: {}", t.getMessage(), t);
                }
            }
        };
        // 
        statisticsThreadPool.prestartAllCoreThreads();
    }
}
```

# 设置线程数
我们知道任务一般有两种：CPU密集型和IO密集型。

- CPU密集型任务，线程数不宜过多，一般选择**==核心数+1==**或者**==核心数*2==**是比较合理的一个值。因此我们可以考虑将：
  - corePoolSize设置为：核心数+1，
  - maxPoolSize设置为：核心数*2。
- IO密集型任务，我们可以考虑以**==核心数*4==**作为核心线程数，然后**==核心数*5==**作为最大线程数的方式去设置线程数，这样的设置会比直接拍脑袋设置一个值会更合理一些。

当然总的线程数不宜过多，控制在100个线程以内比较合理，否则线程数过多可能会导致频繁地上下文切换，导致系统性能反不如前。

# 正确关闭
为了实现优雅停机，应当先调用shutdown方法，线程池不会再接收任何新的任务，但是已提交的任务还会继续执行，包括队列中的。

之后还应当调用awaitTermination方法，这个方法可以设定线程池在关闭之前的最大超时时间，如果在超时时间结束之前线程池能够正常关闭，这个方法会返回true，否则，一旦超时，就会返回false。通常来说我们不可能无限制地等待下去，因此需要事先预估一个合理的超时时间，然后去使用这个方法。

如果awaitTermination方法返回false，又希望尽可能在线程池关闭之后再做其他资源回收工作，可以考虑再调用一下shutdownNow方法，此时队列中所有尚未被处理的任务都会被丢弃，同时会设置线程池中每个线程的中断标志位。

shutdownNow并不保证一定可以让正在运行的线程停止工作，除非提交给线程的任务能够正确响应中断。到了这一步，可以考虑继续调用awaitTermination方法，或者直接放弃，去做接下来要做的事情。

# 其他有用方法
大家可能有留意到，我在创建线程池的时候，还调用了这个方法：prestartAllCoreThreads。这个方法有什么作用呢？我们知道一个线程池创建出来之后，在没有给它提交任何任务之前，这个线程池中的线程数为0。有时候我们事先知道会有很多任务会提交给这个线程池，但是等它一个个去创建新线程开销太大，影响系统性能，因此可以考虑在创建线程池的时候就将所有的核心线程全部一次性创建完毕，这样系统起来之后就可以直接使用了。

其实线程池中还提供了其他一些比较有意思的方法。比如我们现在设想一个场景，当一个线程池负载很高，快要撑爆导致触发拒绝策略时，有没有什么办法可以缓解这一问题？其实是有的，因为线程池提供了设置核心线程数和最大线程数的方法，它们分别是setCorePoolSize方法和setMaximumPoolSize方法。是的，**线程池创建完毕之后也是可以更改其线程数的！**因此，面对线程池高负荷运行的情况，我们可以这么处理：

1. 起一个定时轮询线程（守护类型），定时检测线程池中的线程数，具体来说就是调用getActiveCount方法
2. 当发现线程数超过了核心线程数大小时，可以考虑将CorePoolSize和MaximumPoolSize的数值同时乘以2，当然这里不建议设置很大的线程数，因为并不是线程越多越好的，可以考虑设置一个上限值，比如50, 100之类的。
3. 同时，去获取队列中的任务数，具体来说是调用getQueue方法再调用size方法。当队列中的任务数少于队列大小的二分之一时，我们可以认为现在线程池的负载没有那么高了，因此可以考虑在线程池先前有扩容过的情况下，将CorePoolSize和MaximumPoolSize还原回去，也就是除以2。

以上是我个人建议的一种使用线程池的方式。

# 线程池是最佳方案吗？
线程池并非在任何情况下都是性能最优的方案。如果是一个追求极致性能的场景，可以考虑使用Disruptor高性能队列。单纯基于JDK的话会不会有更好地方案？答案是有的。

在一个线程池中，多个线程是共用一个队列的，因此在任务很多的情况下，需要对这个队列进行频繁读写，为了防止冲突因此需要加锁。事实上在阅读线程池源代码的时候就可以发现，里面充斥着各种加锁的代码，那有没有更好的实现方式呢？

其实我们可以考虑创建一个由单线程线程池构成的列表，每个线程池都使用有界队列这种方式去实现多线程。这么做的好处是，每个线程池中的队列都只会被一个线程去操作，这样就没有竞争的问题。

其实这种用空间换时间的思路借鉴了Netty中的EventLoop的实现机制。试想，如果线程池的性能真的有那么好，为什么Netty不用呢？

# 其他注意点
1. 任何情况下都==不应该使用==可伸缩线程池（线程的创建和销毁开销是很大的）
2. 任何情况下都不应该使用无界队列，单测除外（有界队列常用的有ArrayBlockingQueue和LinkedBlockingQueue，前者基于数组实现，后者基于链表。从性能表现上来看，LinkedBlockingQueue的吞吐量更高但是性能并不稳定，实际情况下应当使用哪一种建议自行测试之后决定。顺便说一句，Executors的newFixedThreadPool采用的是LinkedBlockingQueue）
3. 推荐自行实现RejectedExecutionHandler，JDK自带的都不是很好用，你可以在里面实现自己的逻辑。如果需要一些特定的上下文信息，你可以在Runnable实现类中添加一些自己的东西，这样在RejectedExecutionHandler中就可以直接使用了。

# 怎样做到不丢任务
这里其实指的是一种特殊情况，就是比如突然遇到了一股流量尖峰，导致线程池负载已经非常高了，即快要触发拒绝策略的时候，我们可以怎么做来尽量防止提交的任务不会丢失。一般来说当遇到这种情况的时候，应当尽快触发报警通知研发人员来处理。之后不管是限流也好，还是增加机器也好，甚至是上kafka，redis甚至是数据库用来暂存任务数据也是可以的，但毕竟远水救不了近火，如果我们希望在正式解决这个问题之前，先尽可能地缓解，可以考虑怎么做呢？

首先可以考虑的就是我前面有提过的动态增大线程池中的线程数，但是假如说已经扩容过了，此时不应继续扩容，否则可能导致系统的吞吐量更低。在这种情况下，应当自行实现RejectedExecutionHandler，具体来说就是在实现类中，单独开一个单线程的线程池，然后调用原线程池的getQueue方法的put方法，将塞不进去的任务再次尝试塞进去。当然在队列满的时候是塞不进去的，但那至少也只是阻塞了这个单独的线程而已，并不影响主流程。

当然，这种方案是治标不治本的，面对流量激增这种场景其实业界有很多成熟的做法，只是单纯从线程池的角度来看的话，这种方式不失为一种临时的解决方案。
